inherit_from: .rubocop_todo.yml

AllCops:
    EnabledByDefault: true
    Exclude:
        - 'vendor/bundle/**/*'
        - 'rails_generators/gruff/**/*'

Gemspec/OrderedDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/CommentIndentation:
  Enabled: false

Layout/FirstMethodArgumentLineBreak:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Lint/NumberConversion:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/FormatString:
  EnforcedStyle: sprintf

Style/FormatStringToken:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/IfUnlessModifier:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/Next:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false
